# -- 코드를 입력하세요
# WITH BOOK_INFO AS (
# SELECT B.*, S.SALES * B.PRICE AS BOOK_SALES
# FROM 
#     BOOK B
# INNER JOIN
#     (SELECT BOOK_ID, SALES
#     FROM BOOK_SALES
#     WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') S
#     ON B.BOOK_ID = S.BOOK_ID
# GROUP BY B.AUTHOR_ID, B.BOOK_ID
# ORDER BY B.AUTHOR_ID, B.BOOK_ID)

# SELECT B.AUTHOR_ID, AUTHOR_NAME, B.CATEGORY, B.BOOK_SALES
# # , SUM(B.BOOK_SALES) AS TOTAL_SALES
# FROM AUTHOR A, BOOK_INFO B
# WHERE
#     A.AUTHOR_ID = B.AUTHOR_ID
# # GROUP BY A.AUTHOR_ID
# # ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC


# SELECT B.*, S.SALES_DATE, S.SALES, S.SALES * B.PRICE AS BOOK_SALES
# FROM 
#     BOOK B
# INNER JOIN
#     (SELECT BOOK_ID, SALES, SALES_DATE
#     FROM BOOK_SALES
#     WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') S
#     ON B.BOOK_ID = S.BOOK_ID
# GROUP BY B.AUTHOR_ID, B.BOOK_ID
# ORDER BY B.AUTHOR_ID, B.BOOK_ID

WITH BOOK_INFO AS (
SELECT S.*, B.CATEGORY, B.AUTHOR_ID, B.PRICE, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
    LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID, CATEGORY)

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM BOOK_INFO B
INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
ORDER BY B.AUTHOR_ID, CATEGORY DESC

    