-- 코드를 작성해주세요
# SELECT ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO
# WHERE ITEM_ID NOT IN (
#     SELECT PARENT_ITEM_ID
#     FROM ITEM_TREE IT
#         LEFT JOIN ITEM_INFO II ON IT.PARENT_ITEM_ID = II.ITEM_ID
#     WHERE PARENT_ITEM_ID IS NOT NULL)
# ORDER BY ITEM_ID DESC

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
    LEFT JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC