-- 코드를 입력하세요
SELECT DISTINCT U.USER_ID, U.NICKNAME, 
    CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS 전체주소, 
    CONCAT(SUBSTR(TLNO, 1, 3), "-", SUBSTR(TLNO, 4, 4), "-", SUBSTR(TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER U
    INNER JOIN USED_GOODS_BOARD B ON U.USER_ID = B.WRITER_ID
WHERE U.USER_ID IN (SELECT WRITER_ID
                    FROM USED_GOODS_BOARD
                    GROUP BY WRITER_ID
                    HAVING COUNT(*) >= 3)
ORDER BY U.USER_ID DESC