-- 코드를 입력하세요
WITH RENT_HISTORY AS (
    SELECT 
        HISTORY_ID, 
        H.CAR_ID,
        C.DAILY_FEE,
        C.CAR_TYPE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS RENT_DAYS
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        INNER JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE 
        H.CAR_ID IN (SELECT CAR_ID 
                       FROM CAR_RENTAL_COMPANY_CAR 
                       WHERE CAR_TYPE = '트럭')
),
MATCHED_DISCOUNT AS (
    SELECT 
        H.HISTORY_ID,
        H.DAILY_FEE,
        H.RENT_DAYS,
        D.DISCOUNT_RATE
    FROM 
        RENT_HISTORY H
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
        ON D.CAR_TYPE = H.CAR_TYPE
        AND CAST(REPLACE(DURATION_TYPE, "일 이상", "") AS UNSIGNED) =(
            SELECT MAX(CAST(REPLACE(DURATION_TYPE, "일 이상", "") AS UNSIGNED))
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D2
            WHERE D2.CAR_TYPE = H.CAR_TYPE
                AND CAST(REPLACE(DURATION_TYPE, "일 이상", "") AS UNSIGNED) <= H.RENT_DAYS
        )
)

SELECT
    HISTORY_ID,
    FLOOR((DAILY_FEE * (100 - IFNULL(DISCOUNT_RATE, 0)) / 100) * RENT_DAYS) AS FEE
FROM MATCHED_DISCOUNT
ORDER BY FEE DESC, HISTORY_ID DESC

# SELECT *
# FROM RENT_HISTORY