-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO,  A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A, PATIENT P, DOCTOR D
WHERE DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
    AND A.APNT_CNCL_YN LIKE 'N'
    AND A.MCDP_CD LIKE 'CS'
    AND A.PT_NO = P.PT_NO
    AND A.MDDR_ID = D.DR_ID
ORDER BY A.APNT_YMD;