-- 코드를 입력하세요
WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR +1
    FROM TIME
    WHERE HOUR < 23
)
SELECT T.HOUR, IFNULL(OUT_COUNT, 0) AS COUNT
FROM TIME T
    LEFT JOIN (
        SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS OUT_COUNT
        FROM ANIMAL_OUTS
        GROUP BY HOUR(DATETIME)) O
    ON T.HOUR = O.HOUR
ORDER BY HOUR
