-- 코드를 작성해주세요
WITH AVG_GRADE AS (
    SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT HE.EMP_NO, HE.EMP_NAME,
    CASE
        WHEN AG.AVG_SCORE >= 96 THEN 'S'
        WHEN AG.AVG_SCORE >= 90 THEN 'A'
        WHEN AG.AVG_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END GRADE,
    CASE
        WHEN AG.AVG_SCORE >= 96 THEN HE.SAL * 0.2
        WHEN AG.AVG_SCORE >= 90 THEN HE.SAL * 0.15
        WHEN AG.AVG_SCORE >= 80 THEN HE.SAL * 0.1
        ELSE 0
    END BONUS
FROM HR_EMPLOYEES HE
    INNER JOIN AVG_GRADE AG ON HE.EMP_NO = AG.EMP_NO
ORDER BY HE.EMP_NO
