-- 코드를 입력하세요
WITH 
REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW_CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MAX_COUNT AS (
    SELECT MAX(REVIEW_CNT) AS MAX_CNT
    FROM REVIEW_COUNT
),
TOP_REVIEWER AS (
    SELECT MEMBER_ID
    FROM REVIEW_COUNT
    WHERE REVIEW_CNT = (
            SELECT MAX_CNT
            FROM MAX_COUNT)
    LIMIT 1
)
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, 
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM 
    MEMBER_PROFILE M
INNER JOIN
    REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
WHERE
    R.MEMBER_ID IN (
            SELECT MEMBER_ID
            FROM TOP_REVIEWER)
ORDER BY REVIEW_DATE, REVIEW_TEXT
