-- 코드를 작성해주세요
SELECT
    ID, FISH_NAME, LENGTH
FROM
    FISH_INFO A
    INNER JOIN FISH_NAME_INFO N ON N.FISH_TYPE = A.FISH_TYPE
WHERE
    LENGTH = (
        SELECT MAX(LENGTH)
        FROM FISH_INFO B
        WHERE A.FISH_TYPE = B.FISH_TYPE)
ORDER BY
    ID