-- 코드를 입력하세요
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d")
# SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, "%Y")
FROM BOOK
WHERE DATE_FORMAT(PUBLISHED_DATE, "%Y") = 2021
    AND CATEGORY LIKE "인문"