# -- 코드를 작성해주세요
WITH TOTAL_SCORE AS (
    SELECT EMP_NO, YEAR, SUM(SCORE) AS SUM_SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)
SELECT S.SUM_SCORE AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM TOTAL_SCORE S
    INNER JOIN HR_EMPLOYEES E ON E.EMP_NO = S.EMP_NO
WHERE S.SUM_SCORE = (SELECT MAX(SUM_SCORE)
               FROM TOTAL_SCORE)

      

