-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', CONCAT_WS('/', F.BOARD_ID, CONCAT(F.FILE_ID, FILE_NAME, FILE_EXT))) AS FILE_PATH
FROM USED_GOODS_FILE F
    INNER JOIN USED_GOODS_BOARD B ON F.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS)
                 FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC