-- 코드를 입력하세요
SELECT P.CATEGORY, P.PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P
WHERE P.CATEGORY IN ('과자', '국', '김치', '식용유')
    AND P.PRICE = (
        SELECT MAX(PRICE)
        FROM FOOD_PRODUCT
        WHERE CATEGORY = P.CATEGORY
    )
ORDER BY PRICE DESC;